---

- name: Copying Keystone config
  template: src=keystone.conf dest=/etc/keystone/keystone.conf

- name: Create authorization token
  command: openssl rand -hex 10 -out /usr/share/admin_tok.txt
  
- name: Add authorization token to config
  shell: openstack-config --set /etc/keystone/keystone.conf DEFAULT admin_token {{ OS_SERVICE_TOKEN }}
  
- name: Create signing keys and certificates
  command: keystone-manage pki_setup --keystone-user keystone --keystone-group keystone
  
- name: Change ownership of ssl directory
  file: path=/etc/keystone/ssl/ owner=keystone group=keystone state=directory recurse=yes

- name: Change permissions of ssl directory
  shell: chmod -R o-rwx /etc/keystone/ssl
  
- name: Change permissions of ssl directory
  shell: chmod -R 766 /var/log/glance /var/log/keystone /var/log/neutron /var/log/nova
  
- name: Remove startup files
  command: rm -rf /var/log/keynote/*.log

- name: Enable Identity Service to be started at boot
  service: name=openstack-keystone enabled=yes state=started
  
- name: Copying environment admin source file
  template: src=admin-openrc.sh dest=/home/vagrant/admin-openrc.sh