---
- name: Install OpenStack packages
  yum: name={{item}} state=present
  with_items:
   - yum-plugin-priorities
   - http://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-3.noarch.rpm
   - http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
   - openstack-utils
   - openstack-selinux