---
# This playbook deploys base environment for Openstack Icehouse. 

- hosts: ice_openstack_infra 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - ntp-standalone
    - openstack-packages
    - rabbitmq-standalone
    - mysql-client

- hosts: ice_openstack_compute
  user: root
  remote_user: root
  sudo: yes
  roles:
    - ntp-standalone
    - openstack-packages
    - mysql-python
    - mysql-client
    - openstack-nova-compute
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge