---

- name: Install OpenStack component packages
  yum: name={{item}} state=present
  with_items:
   - openstack-keystone
   - python-keystoneclient
   - openstack-glance
   - python-glanceclient
   - openstack-neutron
   - openstack-neutron-ml2
   - openstack-neutron-linuxbridge
   - python-neutronclient
   - openstack-nova-api
   - openstack-nova-cert
   - openstack-nova-conductor
   - openstack-nova-console
   - openstack-nova-novncproxy
   - openstack-nova-scheduler
   - python-novaclient
   - memcached
   - python-memcached
   - mod_wsgi
   - openstack-dashboard
   - openstack-cinder
   - openstack-heat-api
   - openstack-heat-engine
   - openstack-heat-api-cfn