---
- name: Copy the kernel networking update file
  copy: src=sysctl.conf dest=/etc/sysctl.conf

- name: Implement kernel networking changes
  shell: sysctl -q -e -p

- name: Copying Neutron config
  template: src=neutron.conf dest=/etc/neutron/neutron.conf
  
- name: Set Networking Service tenant id
  command: openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_tenant_id $(keystone tenant-list | awk '/ service / { print $2 }')

- name: Copy the ML2 conf
  template: src=ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini
  
- name: Copy the L3 agent conf
  copy: src=l3_agent.ini dest=/etc/neutron/l3_agent.ini

- name: Copy the DHCP agent conf
  copy: src=dhcp_agent.ini dest=/etc/neutron/dhcp_agent.ini

- name: Copy the Metadata agent conf
  template: src=metadata_agent.ini dest=/etc/neutron/metadata_agent.ini

- name: Create symbolic link from ML2 to Neutron plugins
  shell: ln -s plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini

- name: Remove startup files
  command: rm -rf /var/log/neutron/*.log
  
- name: Enable Networking Server Service to be started at boot
  service: name=neutron-server enabled=yes state=started
  
- name: Enable Networking Service Linuxbridge Agent to be started at boot
  service: name=neutron-linuxbridge-agent enabled=yes state=started
  
- name: Enable Networking Service L3 Agent to be started at boot
  service: name=neutron-l3-agent enabled=yes state=started
  
- name: Enable Networking Service DHCP Agent to be started at boot
  service: name=neutron-dhcp-agent enabled=yes state=started
  
- name: Enable Networking Service Metadata Agent to be started at boot
  service: name=neutron-metadata-agent enabled=yes state=started