---
- name: Copying Nova config
  template: src=nova.conf dest=/etc/nova/nova.conf

- name: Remove startup files
  command: rm -rf /var/log/nova/*.log

- name: Enable Compute Service API to be started at boot
  service: name=openstack-nova-api enabled=yes state=started
  
- name: Enable Compute Service CERT to be started at boot
  service: name=openstack-nova-cert enabled=yes state=started
  
- name: Enable Compute Service Console to be started at boot
  service: name=openstack-nova-consoleauth enabled=yes state=started
  
- name: Enable Compute Service Scheduler to be started at boot
  service: name=openstack-nova-scheduler enabled=yes state=started

- name: Enable Compute Service Conductor to be started at boot
  service: name=openstack-nova-conductor enabled=yes state=started
  
- name: Enable Compute Service NoVNCProxy to be started at boot
  service: name=openstack-nova-novncproxy enabled=yes state=started