---

- name: Copying Glance api config
  template: src=glance-api.conf dest=/etc/glance/glance-api.conf

- name: Copying Glance registry config
  template: src=glance-registry.conf dest=/etc/glance/glance-registry.conf
  
- name: Remove startup files
  command: rm -rf /var/log/glance/*.log
  
- name: Enable Glance Service API to be started at boot
  service: name=openstack-glance-api enabled=yes state=started
  
- name: Enable Glance Service to be started at boot
  service: name=openstack-glance-registry enabled=yes state=started